// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkv5J0PgrlKCy5Hpyl_2uNvtsqOpy604',
    appId: '1:35897279938:android:be1f4bac2c24f73e04825b',
    messagingSenderId: '35897279938',
    projectId: 'artenauta',
    storageBucket: 'artenauta.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw6Dbz7HO5OSJMaEnNH42LmE2rFXuHl9Y',
    appId: '1:35897279938:ios:2055b7bf36b2817704825b',
    messagingSenderId: '35897279938',
    projectId: 'artenauta',
    storageBucket: 'artenauta.firebasestorage.app',
    iosBundleId: 'com.example.artenauta',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Lqby-ItLBTO3BRBy7YJwiCK030Ac-UQ',
    appId: '1:35897279938:web:5b9db88f9a38799104825b',
    messagingSenderId: '35897279938',
    projectId: 'artenauta',
    authDomain: 'artenauta.firebaseapp.com',
    storageBucket: 'artenauta.firebasestorage.app',
    measurementId: 'G-HDR19RFWFF',
  );
}
